package com.datarepublic.simplecab.entities;

// Generated 15/05/2018 2:50:32 AM by Hibernate Tools 4.3.1

/**
 * CabTripData generated by hbm2java
 */
public class CabTripData implements java.io.Serializable {

	private CabTripDataId id;

	public CabTripData() {
	}

	public CabTripData(CabTripDataId id) {
		this.id = id;
	}

	public CabTripDataId getId() {
		return this.id;
	}

	public void setId(CabTripDataId id) {
		this.id = id;
	}

}
